# -*- coding: utf-8 -*-
"""assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-E21sV6U_Uu7wmCqEl2cxyJbAyne2H6
"""

# this code was reviewed and corrected by AI (Gemini and ChatGPT)
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv('https://raw.githubusercontent.com/dustywhite7/Econ8310/master/AssignmentData/assignment3.csv')

y = df['meal']
x = df[['Total']]
x,xt,y,yt = train_test_split(x,y,test_size=0.2)
model = XGBClassifier(n_estimators=100,max_depth=5,learning_rate=0.5,objective='binary:logistic')
modelFit = model.fit(x,y)
pred = model.predict(xt)
print("XGBoost Accuracy {}%.".format(accuracy_score(yt,pred)*100))